#! usr/bin/env python3

'''
Python 3.8.3 (default, May 27 2020, 02:08:17)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
'''
#cd almas_interpreter
#python interpreter.py script.al


import os, getpass, sys
from lib.STD_lib import *
from lib.root_lib import *
from src.defpsd import *

try:
	intp = open(sys.argv[1], 'r').readlines()
	nm = sys.argv[1]
	nm = nm[-3:].strip()
	if nm == '.al':
		for lex in intp:
			if lex == '\n':
				lex = ''
			elif lex == 'exit':
				print('yy')
				sys.exit()
			STD_lib(lex)
	else:
		print('It is not almas script ! ')
except:
	pass
else:
	exit()

if __name__ == "__main__":
    print("Almas - Interpreter\n[\"Version 0.0.1\", \"including ali package manager.\"]\n[\"Where space doesn’t matters !\"]")
    while True:
        if psd == '':
        	prmt = '\n'+os.getcwd()+' @@ '+ getpass.getuser()+'\n>>> '
        elif psd == defpsd:
        	prmt = '\n'+os.getcwd()+' @@ '+'root'+'\n>>> '
        pmt = input(prmt)
        pmt = pmt.strip()
        STD_lib(pmt)
        
